### ISSUE TITLE
Unsoudness: reference misalignement

### ISSUE THREAD

**Issue by a1phyr** [hannobraun/inotify-rs#155]
Currently, events are read from a `&mut [u8]` buffer, which has an alignment of `1`, whereas `struct inotify_event` has an alignement of `4`.

Therefore, creating a `&inotify_event` from such a `&[u8]` (as done [here](https://github.com/hannobraun/inotify/blob/b3a7062a732851ac39dfd63ba2bd337dbcff123e/src/events.rs#L156-L162)) may create a misaligned reference, which is undefined behaviour.

**Comment by hannobraun** [comment]
Thank you for pointing this out, @a1phyr!

**Comment by hannobraun** [comment]
Presumably fixed by #171, so I'm going to close. Please note that the fix might not be optimal, and any work on trying to provide a more robust fix would be very appreciated. Please check out [this comment](https://github.com/hannobraun/inotify-rs/pull/171#pullrequestreview-655632788) for more information.
