### ISSUE TITLE
"No space left on device"

### ISSUE THREAD

**Issue by vandenoever** [hannobraun/inotify-rs#34]
I've tried the example on my $HOME directory with 125k folders.

```
fn watch() {
  // Create a channel to receive the events.
  let (tx, rx) = channel();

  // Automatically select the best implementation for your platform.
  // You can also access each implementation directly e.g. INotifyWatcher.
  let w: Result<RecommendedWatcher, Error> = Watcher::new(tx);

  match w {
    Ok(mut watcher) => {
      // Add a path to be watched. All files and directories at that path and
      // below will be monitored for changes.
      let mut r = watcher.watch("/home/oever");
      while let Ok(()) = r {
          // You'll probably want to do that in a loop. The type to match for is
          // notify::Event, look at src/lib.rs for details.
          match rx.recv() {
            Ok(notify::Event{path:Some(path),op:Ok(op)}) => {
                println!("{:?} {:?}", op, path);
            },
            Err(e) => println!("watch error {}", e),
            _ => ()
          }
          println!("next round");
          r = watcher.watch("/home/oever/src");
      }
      if let Err(err) = r {
          println!("Error?: {:?}", err);
      }
    },
    Err(err) => println!("Error!: {:?}", err)
  }
}
```
prints out
```
Error?: Io(Error { repr: Os { code: 28, message: "No space left on device" } })
```
The error occurred in the watch() loop. Inotify had plenty of handles left:
```bash
$ cat /proc/sys/fs/inotify/max_user_watches
524288
```

**Comment by hannobraun** [comment]
Hi, thanks for your report. Some observations:
- Since `inotify-rs` is a thin wrapper around `inotify` and doesn't do anything fancy, I don't think it is responsible for your error. I'm also not much of an expert, but I'll try to help you as best I can.
- It seems you're using [rsnotify](https://github.com/passcod/rsnotify), not `inotify-rs` directly. I don't think `rsnotify` is responsible for your error either, but if we can't rule that out, you might want to open an issue there.
- I'm not convinced that there are plenty of handles left, as you say. `rsnotify` seems to add watches for every directory entry recursively, which probably means you need one handle per file and one handle per directory. Since you say you have 125k directories, the total number might easily be above 524288.

I suggest you count the number of files in your home directory and raise the limit accordingly. A quick search turned up [this answer on StackExchange](http://unix.stackexchange.com/a/13757) on how to do it.

**Comment by vandenoever** [comment]
Increasing the number to 2.5M does solve the issue. I think this is a bug in rsnotify and I'll report it there.

I've tested with `inotifywatch ~ -r` and that works fine when the number of allowed watches is a bit larger than the number of directories, but stops working when it is less.

**Comment by vandenoever** [comment]
I've reported the issues at rsnotify. https://github.com/passcod/rsnotify/issues/69

**Comment by hannobraun** [comment]
Since it seems this is being handled downstream, I'm closing the issue.
