### ISSUE TITLE
event.name is always "" when add_watch is called with a filename instead of a dir

### ISSUE THREAD

**Issue by arsalan86** [hannobraun/inotify-rs#56]
I've been trying to get this to work, but have been unsuccessful. I'm writing a program where I want to monitor a large number of files spread across different paths in the filesystem.

If I pass /path/to/file to add_watch(), the returned event for that watch always contains an empty name field.

I have been able to replicate this with on a variety of environments, with many kinds of target files (with assorted permissions). I have also tried many different watch masks.

As it stands, this library seems broken for use with single file targets, as opposed to dirs.

**Comment by arsalan86** [comment]
This is how Inotify behaves by default for watches that are filenames by default, and not an issue with inotify-rs.

**Comment by hannobraun** [comment]
Thanks for reporting this. I think you're right about this being default inotify behavior.

Theoretically we could keep track of file names in inotify-rs, but I don't think that's a good idea. inotify-rs is meant to be a thin wrapper around inotify and serve as a building block for more high-level libraries.

I can think of two solutions to your problem:
1. Keep track of the file names yourself.
2. Use a higher-level library instead of using inotify-rs directly. [Notify](https://crates.io/crates/notify) is such a library, although I don't know how it handles this particular issue.
